name: Build and Push Docker Images

on:
  push:
    branches:
      - '*' # Trigger on any branch push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allow read access to repository contents
      packages: write # Allow writing to GitHub Packages (ghcr.io)
      id-token: write # Required for OIDC authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token for authentication

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          tags: |
            type=ref,event=branch,enable=true,prefix={{raw}} # Use branch name as tag
            type=sha,format=long # Optional: also tag with SHA

      - name: Build and push dev image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: development # Build the dev stage
          push: true
          tags: ${{ steps.meta.outputs.tags }}-dev # Append -dev to the tag
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push prod image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: runner # Build the production runner stage
          push: true
          tags: ${{ steps.meta.outputs.tags }}-prod # Append -prod to the tag
          labels: ${{ steps.meta.outputs.labels }}
